@Accounts = new Meteor.Collection 'accounts'
@Categories = new Meteor.Collection 'categories'
@Transactions = new Meteor.Collection 'transactions'
@Targets = new Meteor.Collection 'targets'
@Plans = new Meteor.Collection 'plans'
@PlanCategories = new Meteor.Collection 'plan_categories'